openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /categories/:
    get:
      operationId: categories_list
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpenseCategory'
          description: ''
    post:
      operationId: categories_create
      tags:
      - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCategoryWrite'
          description: ''
  /categories/{id}/:
    put:
      operationId: categories_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpenseCategoryWrite'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCategoryWrite'
          description: ''
    patch:
      operationId: categories_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCategoryWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCategoryWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCategoryWrite'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCategoryWrite'
          description: ''
  /categories/{id}/codes/:
    get:
      operationId: categories_codes_list
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpenseCodeWrite'
          description: ''
    post:
      operationId: categories_codes_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCodeWrite'
          description: ''
  /codes/{id}/:
    put:
      operationId: codes_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - codes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpenseCodeWrite'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCodeWrite'
          description: ''
    patch:
      operationId: codes_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - codes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCodeWrite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCodeWrite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedExpenseCodeWrite'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCodeWrite'
          description: ''
components:
  schemas:
    ExpenseCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        is_active:
          type: boolean
        codes:
          type: array
          items:
            $ref: '#/components/schemas/ExpenseCode'
          readOnly: true
      required:
      - codes
      - id
      - name
    ExpenseCategoryWrite:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        is_active:
          type: boolean
      required:
      - id
      - name
    ExpenseCode:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        category_id:
          type: string
          format: uuid
          readOnly: true
        code:
          type: string
          maxLength: 100
        description:
          type: string
        is_active:
          type: boolean
      required:
      - category_id
      - code
      - id
    ExpenseCodeWrite:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        category:
          type: string
          format: uuid
        code:
          type: string
          maxLength: 100
        description:
          type: string
        is_active:
          type: boolean
      required:
      - category
      - code
      - id
    PatchedExpenseCategoryWrite:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        is_active:
          type: boolean
    PatchedExpenseCodeWrite:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        category:
          type: string
          format: uuid
        code:
          type: string
          maxLength: 100
        description:
          type: string
        is_active:
          type: boolean
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
